// export const categories = ["Clothes", "Traditional", "Figures", "Souvenirs"];

export const clothes = [
    {
        id: 1,
        name: "Koi Fish Kimono",
        price: 36.95,
        description: "Elegant Japanese Kimono Cardigan Jacket: This apparel is very pleasant to wear on a daily basis and can be worn all seasons of the year without any inconvenience",
        image: "../assets/products/clothes/koi-fish-kimono.jpg",
        link: "https://japanese-clothing.com/products/koi-fish-kimono",
        rating: 4.6,
        likes: 0,
        visible: true,
    },
    {
        id: 2,
        name: "Crow Flying Kimono",
        price: 36.95,
        description: "High-quality Japanese Kimono Jacket: Product designed with only the best materials for a comfortable feeling on the skin",
        image: "../assets/products/clothes/crow-flying-kimono.jpg",
        link: "https://japanese-clothing.com/products/crow-kimono",
        rating: 4.8, 
        likes: 0,
        visible: true,
    },
    {
        id: 3,
        name: "Tokyo Japan Hoodie",
        price: 46.95,
        description: "Streetwear Japanese Hoodie: This product comes with an original Japanese design and features a Hood, a Drawstring and a Kangaroo Pocket",
        image: "../assets/products/clothes/tokyo-japan-hoodie.jpg",
        link: "https://japanese-clothing.com/products/tokyo-japan-hoodie",
        rating: 4.2,
        likes: 0, 
        visible: true,
    },
    {
        id: 4,
        name: "Moon Dragon Kimono",
        price: 46.95,
        description: "High-quality Japanese Kimono Jacket: Product designed with only the best materials for a comfortable feeling on the skin",
        image: "../assets/products/clothes/moon-dragon-kimono.jpg",
        link: "https://japanese-clothing.com/products/moon-dragon-kimono",
        rating: 4.7, 
        likes: 0,
        visible: true,
    },
    {
        id: 5,
        name: "Wolf Yin Yang Kimono",
        price: 39.95,
        description: "High-quality Japanese Kimono Jacket: Product designed with only the best materials for a comfortable feeling on the skin",
        image: "../assets/products/clothes/wolf-yin-yang-kimono.jpg",
        link: "https://japanese-clothing.com/products/yin-and-yang-wolf-kimono",
        rating: 4.5, 
        likes: 0,
        visible: true,
    },
];