export const figures = [
    {
        id: 1,
        name: "Shinji Ikari Figure",
        price: 149.96,
        description: "Tokyo Figure Shinji Ikari Ver.Radio EVA Part.2 1/7 Figure Evangelion (RADIO EVA)",
        image: "../assets/products/figures/1.jpg",
        link: "https://www.plazajapan.com/4573451878727/",
        rating: 4.7,
        likes: 0,
        visible: true, 
    },
    {
        id: 2,
        name: "Velkhana Figure",
        price: 148.16,
        description: "Capcom Figure Builder Creator's Model Velkhana Figure",
        image: "../assets/products/figures/2.jpg",
        link: "https://www.plazajapan.com/4976219124515/",
        rating: 5.0, 
        likes: 0,
        visible: true,
    },
    {
        id: 3,
        name: "Valphalk Figure",
        price: 148.24,
        description: "Capcom Figure Builder Creator's Model Sky Comet Dragon Valphalk Rage Ver. Figure",
        image: "../assets/products/figures/3.jpg",
        link: "https://www.plazajapan.com/4976219124492/",
        rating: 4.3, 
        likes: 0,
        visible: true,
    },
    {
        id: 4,
        name: "Arcadia Figure",
        price: 103.95,
        description: "ARCADIA MBR-04-Mk.IV Destroid Tomahawk 1/60 Figure (The Super Dimension Fortress Macross)",
        image: "../assets/products/figures/4.jpg",
        link: "https://www.plazajapan.com/4582482821602/",
        rating: 4.8, 
        likes: 0,
        visible: true,
    },
    {
        id: 5,
        name: "Rozemyne Figure",
        price: 237.11,
        description: "Tokyo Figure Rozemyne 1/7 Figure (Ascendance of a Bookworm)",
        image: "../assets/products/figures/5.jpg",
        link: "https://www.plazajapan.com/4573451870677/",
        rating: 4.6, 
        likes: 0,
        visible: true,
    },
];