export const souvenirs = [
    {
        id: 1,
        name: "Golden Temple Fridge Magnet",
        price: 12,
        description: "Kinkaku-ji Temple (The Golden Pavilion) - Kyoto Japan, Souvenir Thailand 3d Resin TOY Fridge Magnet",
        image: "../assets/products/souvenirs/1.jpg",
        link: "https://www.amazon.com/Kinkaku-ji-Temple-Golden-Pavilion-Quality/dp/B00JDP7K3I/ref=sr_1_5?keywords=Japanese+Souvenirs&qid=1677679964&sr=8-5",
        rating: 5, 
        likes: 0,
        visible: true,
    },
    {
        id: 2,
        name: "Stylized Glass",
        price: 9.99,
        description: "Sudopo GUNCENG Collectible Shot Glass Japanese Sightseeing Memory Design",
        image: "../assets/products/souvenirs/2.jpg",
        link: "https://www.amazon.com/Collectible-Japanese-Sightseeing-Memory-Design/dp/B01N6EG8ID/ref=sr_1_9?keywords=Japanese+Souvenirs&qid=1677679964&sr=8-9",
        rating: 4.1, 
        likes: 0,
        visible: true,
    },
    {
        id: 3,
        name: "Bamboo Silk Fan",
        price: 5.49,
        description: "Japanese Fan Handmade Decorative Accessories - Folding Fan Vintage Hand Fans for Women Portable Folding Fan Bamboo Silk Fan - Japanese Decorations Retro Fans - Kanagawa Wave Foldable Fan Handheld",
        image: "../assets/products/souvenirs/3.jpg",
        link: "https://www.amazon.com/Japanese-Fan-Handmade-Decorative-Accessories/dp/B003VMUOMI/ref=sr_1_10?keywords=Japanese+Souvenirs&qid=1677679964&sr=8-10",
        rating: 3.7, 
        likes: 0,
        visible: true,
    },
    {
        id: 4,
        name: "Lucky Cat",
        price: 32.46,
        description: "\"9\" Waving Lucky Fortune Cat Maneki Neko Japanese Porcelain Lucky Cat H21CM",
        image: "../assets/products/souvenirs/4.jpg",
        link: "https://www.amazon.com/Waving-Fortune-Maneki-Japanese-Porcelain/dp/B0763QYHGM/ref=sr_1_17_sspa?keywords=Japanese+Souvenirs&qid=1677679964&sr=8-17-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyQzRNTTlNN0pRSURSJmVuY3J5cHRlZElkPUEwMjk4NjkwM0w4UDQxNTgyT1ZZTSZlbmNyeXB0ZWRBZElkPUEwODQ3NDgzSkgxM1lKSlZVRVlIJndpZGdldE5hbWU9c3BfbXRmJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ==",
        rating: 4.0, 
        likes: 0,
        visible: true,
    },
    {
        id: 5,
        name: "Makineko Magnet",
        price: 9.99,
        description: "Japanese Manekineko (Beckoning Cat) Design Magnet",
        image: "../assets/products/souvenirs/5.jpg",
        link: "https://www.amazon.com/Japanese-Manekineko-Beckoning-Design-Magnet/dp/B01EHFQCXC/ref=sr_1_54?keywords=Japanese+Souvenirs&qid=1677679964&sr=8-54",
        rating: 4.9, 
        likes: 0,
        visible: true,
    },
];