export const traditional = [
    {
        id: 1,
        name: "Ancient Painting",
        price: 375,
        description: "Ema -Japanese Votive painting of a Woman and a Boy",
        image: "../assets/products/traditional/1.webp",
        link: "https://shibui.com/products/ema-japanese-votive-painting-of-a-woman-and-a-boy",
        rating: 4.8, 
        likes: 0,
        visible: true,
    },
    {
        id: 2,
        name: "Inari Foxes",
        price: 1600,
        description: "Pair of Japanese Inari Foxes Cast in Bronze",
        image: "../assets/products/traditional/2.webp",
        link: "https://shibui.com/products/pair-of-japanese-inari-foxes-cast-in-bronze",
        rating: 5,
        likes: 0,
        visible: true,
    },
    {
        id: 3,
        name: "Buddhism Figure",
        price: 255,
        description: "Ebisu Fisherman's God - Good Luck Figure",
        image: "../assets/products/traditional/3.webp",
        link: "https://shibui.com/products/ebisu-fishermans-god-good-luck-figure",
        rating: 4.9, 
        likes: 0,
        visible: true,
    },
    {
        id: 4,
        name: "Guardian Figures",
        price: 15_000,
        description: "Sadaijin & Udaijin Antique Japanese Guardian Figures",
        image: "../assets/products/traditional/4.webp",
        link: "https://shibui.com/products/antique-japanese-guardian-figures",
        rating: 4.7, 
        likes: 0,
        visible: true,
    },
    {
        id: 5,
        name: "Buddhist Bell",
        price: 380,
        description: "Antique Orin Buddhist Bell",
        image: "../assets/products/traditional/5.webp",
        link: "https://shibui.com/products/antique-orin-buddhist-bell-4",
        rating: 4.5, 
        likes: 0,
        visible: true,
    },
];